### ISSUE TITLE
Allow users to type operators easily

### ISSUE THREAD

**Issue by frogrammer** [UMM-CSci/edsger#14]
Implement a sidebar of buttons so that users can type operator symbols easily.
The following symbols are supported: `∨, ∧, ¬, ≡, and ⇒`

**Comment by frogrammer** [comment]
Instead of buttons, replace symbols dynamically as users are typing.
`!` to `¬`
`&` to `∧`
`|` to `∨`
`=` to `≡`
`=>` to `⇒`

**Comment by lverns** [comment]
Should we do `==` to `≡` since we might want to add the ability to do `=` alone in the future?
