### ISSUE TITLE
Add project license

### ISSUE THREAD

**Issue by lverns** [UMM-CSci/edsger#25]
The README currently the license is "to be announced", but `project.clj` says it is [EPL](http://www.eclipse.org/legal/epl-v10.html).

We should decide on a license and make sure we specify it consistently in  `README`, `project.clj`, and  `LICENSE`.

**Comment by frogrammer** [comment]
`figwheel`, `doo`, and `instaparse` all use EPL license. I think it makes sense for us to go by EPL?
